#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Oct 26 22:19:47 CEST 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto e42effbf65754a4f99dae98433ee4e2b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot aal1_gen_tb_behav xil_defaultlib.aal1_gen_tb -log elaborate.log"
xelab -wto e42effbf65754a4f99dae98433ee4e2b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot aal1_gen_tb_behav xil_defaultlib.aal1_gen_tb -log elaborate.log

